### ISSUE TITLE
Not all underscores are replaced with dashes for PyPi packages

### ISSUE THREAD

**Issue by ghost** [package-url/packageurl-js#23]
Hello.

We have used the library and it works good for us in most of cases.

But we noticed the following issue: according to the pURL specification, for PyPi packages all underscores "_" must be replaced with dashes "-" in the name. However, it seems as if only the first occurrence is replaced using "someString.replace(...)".

Can you please have a look at this?
(There are also other usages of replace function.)

Thank you very much,
Pavel

**Comment by DarthHater** [comment]
@pkomardin , myself and @declanhunter took a gander at this today, and fixed JUST the pypi issue (trying to keep the PR narrow). It's at #26 if you wanted to take a gander. If you find other issues, I'd raise them! Thanks for raising this.

**Comment by ghost** [comment]
... hi, thank you for having fixed that!!! We are looking forward for the next library version.

**Comment by steven-esser** [comment]
@pkomardin @DarthHater @declanhunter v0.0.6 of `packageurl-js` published to NPM, with your fix to this issue included: https://www.npmjs.com/package/packageurl-js/v/0.0.6

Thanks for the contribution!
