### ISSUE TITLE
Validate that `namespace` is provided for Maven purls

### ISSUE THREAD

**Issue by rgmz** [package-url/packageurl-js#29]
It's currently possible to create an 'invalid' Maven purl because it doesn't validate the namespace.
https://github.com/package-url/packageurl-js/blob/6ca60fc79cbbae7665cfedc4bc3a640e07fffea3/src/package-url.js#L53

This functionality is included in the Java package, so presumably we want parity with other implementations.
https://github.com/package-url/packageurl-java/blob/bd3241aaa27ea297766a0a99e48b48ca17465956/src/main/java/com/github/packageurl/PackageURL.java#L561-L567

**Comment by jdalton** [comment]
This is fixed on master branch.
