### ISSUE TITLE
Handle qualifiers with a string value

### ISSUE THREAD

**Issue by steven-esser** [package-url/packageurl-js#4]
Currently we throw an exception when creating a packageURL with `qualifiers` that are strings. 

The python version currently handles this, so the JS version should as well.

**Comment by Omkaragrawal** [comment]
Hey,
Does creating Purl with qualifiers that are string means something like:

pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?repository_url=repo.spring.io/\\"release\\"
or something similar?
Sorry to ask if this is a silly question.

**Comment by jkowalleck** [comment]
Qualifiers are expected to be a dictionary of strings. see https://github.com/package-url/packageurl-js/blob/9998e463ba5e4ad0be96b52e12497d089bdb0b97/src/package-url.d.ts#L68C3-L70

the described feature would bean, that you could set the property to `'foo=1&bar=baz'` and it would be internally converted to a dictionary: `{foo:1,bar:'baz'}`

**Comment by jdalton** [comment]
Fixed by https://github.com/package-url/packageurl-js/pull/73, specifically https://github.com/package-url/packageurl-js/pull/73/commits/978280e48c0ab599a8489ea5390c5dd4039dfb4a.

**Comment by jdalton** [comment]
Closed by #73

**Comment by jdalton** [comment]
[v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) has been published 🎉
