### ISSUE TITLE
Throws an error for scoped npm package purls

### ISSUE THREAD

**Issue by ajmalab** [package-url/packageurl-js#44]
Parsing npm purls such as `pkg:npm/@godaddy/terminus@4.11.2` throws the following error: `Error: purl is missing the required "name" component.`

**Comment by kikar** [comment]
@ajmalab I think `@` is an invalid char in purl name. Should be `pkg:npm/%40godaddy/terminus@4.11.2`

**Comment by ajmalab** [comment]
You are right, missed this line in the Purl spec. Closing the issue.
