### ISSUE TITLE
PackageURL.fromString() failure when name starts with colon character

### ISSUE THREAD

**Issue by vladh1** [package-url/packageurl-js#45]
`const purlString = new PackageURL('generic', null, ':name', '1.0.0').toString();`
`const purl = PackageURL.fromString(purlString);`

The second line fails to parse the purl string with the error:
 Error: purl is missing the required "type" component.

**Comment by aniruth37** [comment]
Raised #55 to fix this

**Comment by steven-esser** [comment]
`v1.2.1` released to npm with the fix
