### ISSUE TITLE
versions beginning with special characters should throw an error

### ISSUE THREAD

**Issue by topaztee** [package-url/packageurl-js#48]
I dont believe versions can begin with special characters: 
eg.  `pkg:npm/foo@!` `pkg:npm/foo@;` `pkg:npm/foo@{ should throw an error.

**Comment by mcombuechen** [comment]
According to the [PackageURL specification](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst):

> A version must be a percent-encoded string

This is currently not the case in the current implementation. While the `fromString()` method decodes the version string, the `toString()` method of a purl instance will replace percent-encoded symbols such as `:` from `%3A` back to `:`; making it not fully decoded.

Similar issues have already been raised [here](https://github.com/package-url/packageurl-js/issues/45) and [here](https://github.com/package-url/packageurl-js/issues/46). What was the initial reasoning about this logic?

**Comment by satanshiro** [comment]
Hi @mcombuechen 
I am facing a weird problem with this chage, why is this the corect behavior? I think from string was fairly straightforward, now we have to encode only the version part of a purl string in order for it to work 
for example this will fail:
'pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?arch=amd64&distro=debian-10'
but this is still how most sbom vendors send data
