### ISSUE TITLE
fromString(): version is used outside of block scope

### ISSUE THREAD

**Issue by mscudlik** [package-url/packageurl-js#5]
In method fromString() the version variable is used in line 147 to construct a new object,
but the variable is declared with a block scope inside an if statement (line 123).

This is an issue when using packageurl-js from typescript:
https://www.typescriptlang.org/docs/handbook/variable-declarations.html#block-scoping

As a consequence, fromString() always throws an error using typescript:

```
message:"version is not defined"
stack:"ReferenceError: version is not defined
```

**Comment by steven-esser** [comment]
@mscudlik Would https://github.com/package-url/packageurl-js/pull/8 fix this?
