### ISSUE TITLE
Validate pub (dart) types according to spec

### ISSUE THREAD

**Issue by topaztee** [package-url/packageurl-js#50]
https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#pub

We should validate as the spec suggests the purls of pub type, 
It states:

>  Pub normalizes all package names to be lowercase and using underscores. The only allowed characters are [a-z0-9_].

**Comment by steven-esser** [comment]
@topaztee `v1.2.0` published with you changes. Thank you for the contribution! 

https://www.npmjs.com/package/packageurl-js/v/1.2.0

**Comment by topaztee** [comment]
thats great to hear :)
