### ISSUE TITLE
purls with + in versions are not accepted 

### ISSUE THREAD

**Issue by satanshiro** [package-url/packageurl-js#52]
Any of the following purls will fail in the latest version
pkg:pypi/torchaudio@2.0.1+cpu
pkg:deb/debian/gettext-base@0.19.8.1-2+deb9u1?arch=amd64&upstream=gettext&distro=debian-9
pkg:deb/debian/libprocps3@2:3.3.9-9+deb8u1?arch=amd64&upstream=procps&distro=debian-8
pkg:deb/debian/libssl1.1@1.1.1n-0+deb10u3?arch=amd64&upstream=openssl&distro=debian-10

any purl that has a plus sign will fail with the error:
Invalid purl: version must be percent-encoded

**Comment by satanshiro** [comment]
@steven-esser @mcombuechen 
I added a pr please let me know what you think, this can save time. 
we cannot update to latest with current version.
thank you and have a nice day

**Comment by steven-esser** [comment]
comments left on https://github.com/package-url/packageurl-js/pull/53

**Comment by steven-esser** [comment]
v1.2.1 released to npm with the fix
