### ISSUE TITLE
Incorrect parsing of PURLs begining with `pkg://`

### ISSUE THREAD

**Issue by matt-phylum** [package-url/packageurl-js#58]
The PURL test suite contains the PURL `pkg://maven/org.apache.commons/io` which is supposed to parse as a namespace of `org.apache.commons` and a name of `io`, but packageurl-js parses it as having no namespace. The namespace just disappears. It doesn't become part of the name.

**Comment by aniruth37** [comment]
Raised https://github.com/package-url/packageurl-js/pull/62 to fix this

**Comment by jdalton** [comment]
Cannot reproduce bug given the example above:
https://github.com/package-url/packageurl-js/pull/62#issuecomment-2115067509

**Comment by matt-phylum** [comment]
This is still reproducible with the given example.

**Comment by jdalton** [comment]
Ah, my bad. @matt-phylum you are correct.

**Comment by jdalton** [comment]
Fixed in master branch.
