### ISSUE TITLE
Qualifiers are case sensitive

### ISSUE THREAD

**Issue by matt-phylum** [package-url/packageurl-js#59]
The PURL test suite contains the PURL `pkg:gem/jruby-launcher@1.1.2?Platform=java` which is supposed to parse as having a qualifier `platform=java`, but packageurl-js parses it as `Platform=java`. This will cause problems if code uses packageurl-js to look for the value of a qualifier.

**Comment by jdalton** [comment]
This is fixed in master branch.

**Update:**
[v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) has been published 🎉
