### ISSUE TITLE
Package types are case sensitive

### ISSUE THREAD

**Issue by matt-phylum** [package-url/packageurl-js#60]
The PURL test suite contains a PURL `pkg:PYPI/Django_package@1.11.1.dev1`. packageurl-js parses this as type `PYPI` instead of the expected `pypi`.

This causes two problems:
1. Code that is looking for `pypi` PURLs won't see them.
2. The pypi-specific name normalization rules that packageurl-js implements for `pypi` are not applied, so the package name comes out as `Django_package` instead of the expected `django-package`.

**Comment by jdalton** [comment]
@matt-phylum  I see you've opened a few issues. Thank you!
Do you have bandwidth for opening PRs too? That would be helpful.

**Comment by jdalton** [comment]
Fixed in master branch.

**Comment by jdalton** [comment]
[v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) has been published 🎉
