### ISSUE TITLE
Incorrect parsing of PURL with leading '/' in namespace

### ISSUE THREAD

**Issue by Moullisha** [package-url/packageurl-js#63]
PackageURL.fromString("pkg:golang//github.com/ll/xlog@2.0") throws the below error:

purl is missing the required "type" component

**Comment by jdalton** [comment]
Resolved on master branch.

**Comment by aniruth37** [comment]
@jdalton Any idea when this would be published in npm?

**Comment by jdalton** [comment]
@aniruth37
> @jdalton Any idea when this would be published in npm?

I don't control that but after the next batch of patches lands I'll inquire!

**Comment by jdalton** [comment]
[v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) has been published 🎉
