### ISSUE TITLE
Invalid purl: version must be percent-encoded

### ISSUE THREAD

**Issue by kennylam91** [package-url/packageurl-js#64]
Hi, I encounter this error: **Invalid purl: version must be percent-encoded** when parse the purl `pkg:npm/@vue/vue-loader-v15@15.11.1` with method `PackageURL.fromString()`.
This purl was validated successfully by other library mvn:packageurl-java@1.4.1 in the backend.

When I look into the code of packageurl-js, I see this:

```
if (p.includes('@')) {
    let f = p.indexOf('@'),
      u = p.substring(f + 1)
    a = decodeURIComponent(u)
    let y = encodeURIComponent(a).replace(/%3A/g, ':').replace(/%2B/g, '+')
    if (u !== y)
      throw new Error('Invalid purl: version must be percent-encoded')
    i = p.substring(0, f)
}
```

I think it could have an issue because method indexOf() return the first matched index, but in this case  `pkg:npm/@vue/vue-loader-v15@15.11.1`, it has another @ so f+1 is not the start of version substring.

**Comment by steven-esser** [comment]
@kennylam91 Thanks for the bug report, will take a look.

**Comment by jdalton** [comment]
This is fixed on master branch.

**Comment by kennylam91** [comment]
OK cool, will it be rolled out soon?

**Comment by jdalton** [comment]
@kennylam91 
> will it be rolled out soon?

I don't control that but after the next batch of patches lands I'll inquire!

**Comment by jdalton** [comment]
[v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) has been published 🎉
