### ISSUE TITLE
Invalid purl passes as valid

### ISSUE THREAD

**Issue by surendrapathak** [package-url/packageurl-js#66]
PURL - `'pkg:maven/org.apache.commons:io@1.3.4'`  passes as valid

> p.PackageURL.fromString('pkg:maven/org.apache.commons:io@1.3.4')
PackageURL {
  type: 'maven',
  name: 'org.apache.commons:io',
  namespace: null,
  version: '1.3.4',
  qualifiers: null,
  subpath: null
}

However, it shouldn't be because the namespace is not percent-encoded.

**Comment by jdalton** [comment]
If you `.toString()` it then it's encoded:
```js
p.PackageURL.fromString('pkg:maven/org.apache.commons:io@1.3.4').toString()
// => 'pkg:maven/org.apache.commons%3Aio@1.3.4'
```

**Comment by surendrapathak** [comment]
Hi @jdalton - The concern is that PURL such as:

`pkg:maven/org.apache.commons:io@1.3.4`

should be marked [invalid](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst) for violating the namespace rule:
<img width="1041" alt="Screenshot 2024-05-19 at 2 20 52 PM" src="https://github.com/package-url/packageurl-js/assets/1686327/6093d3f2-579c-4c3e-91ec-22dc053e3bbc">

However, because packageurl-js parses these successfully, they show up in SBOM as valid entries, causing identification issues.

**Comment by jdalton** [comment]
The exact maven examples fails on master branch with:
```
Error Invalid purl: maven requires a "namespace" field.
```
If adding a namespace/name:
```js
PackageURL.fromString('pkg:maven/org.apache.commons:io/foo@1.3.4')
```
will still allow it as parsing tends to be more lenient as they become arguments to feed to the `new PackageURL(...)`  constructor. When the purl instance is converted `toString()` it is encoded.

Both
```js
PackageURL.fromString('pkg:maven/org.apache.commons:io/foo@1.3.4')
PackageURL.fromString('pkg:maven/org.apache.commons%3Aio/foo@1.3.4')
```
Produce the same result:
```js
PackageURL {
  type: 'maven',
  name: 'foo',
  namespace: 'org.apache.commons:io',
  version: '1.3.4',
  qualifiers: undefined,
  subpath: undefined
}
```
This is by design.

**Comment by surendrapathak** [comment]
Thanks for the note @jdalton 

I am getting these:

```js
 PackageURL {
  type: 'maven',
  name: 'org.apache.commons:io',
  namespace: null,
  version: '1.3.4',
  qualifiers: null,
  subpath: null
}
```

and
```js
PackageURL {
  type: 'maven',
  name: 'foo',
  namespace: 'org.apache.commons:io',
  version: '1.3.4',
  qualifiers: null,
  subpath: null
}
```

You can see that in the first case without a valid package name ('foo'), the entire _intended namespace_ ('org.apache.commons:io') is being treated as a name.

This is why the specification required each namespace segment to be percent-encoded. 
I understand it is designed this way, but it will indeed create confusion without strict enforcement of the PURL spec.

**Comment by jdalton** [comment]
@surendrapathak  I typo'd the example 🤦 . It was supposed to be:
```js
PackageURL.fromString('pkg:maven/org.apache.commons:io/foo@1.3.4')
PackageURL.fromString('pkg:maven/org.apache.commons%3Aio/foo@1.3.4')
```
with the namespace as master branch will throw an error for maven purls without a namespace.

As stated before encoding is done at the `toString()` level. The folks behind the PURL spec side with encoding just enough to prioritize human readability. You can see this in how [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) are stored human readable and then encoded when the `.toString()` method is called

**Comment by surendrapathak** [comment]
Thanks! 

🥇2.0.0 correctly flags the one without the name and matches the spec! 

I appreciate the change around it. 

<img width="500" alt="Screenshot 2024-08-19 at 4 58 32 PM" src="https://github.com/user-attachments/assets/2d47a27c-11e6-4b23-ab9e-9cfc4ac7973e">

**Comment by jdalton** [comment]
@surendrapathak Yay! [v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) ftw 🎉
