### ISSUE TITLE
Add support for parsing namespaces without "name" fields

### ISSUE THREAD

**Issue by bteng22** [package-url/packageurl-js#67]
## Context

My team uses packageurl-js and needs to handle use cases where we're creating configuration options to deny all packages under a specific namespace. We currently use packageurl-js to parse all of our PURLs (including namespaces i.e. `pkg:maven/com.fasterxml.jackson.core/`) and it'd be helpful to have an interface that will allow us use the same parser for these options.

## Current Behavior 

The current packageurl-js library expects a "name" field to be present in the package URL.

## Desired Behavior 

We would like to be able to create and parse package URLs that have a "namespace" field, but no "name" field.

**Comment by jdalton** [comment]
Fixed by https://github.com/package-url/packageurl-js/pull/73 which exposes `PackageURL.parseString()` (https://github.com/package-url/packageurl-js/pull/73/commits/c581ca0e600058b451555972051b7842bb8a56d1)

**Comment by jdalton** [comment]
Closed by #73

**Comment by jdalton** [comment]
[v2.0.0](https://www.npmjs.com/package/packageurl-js/v/2.0.0) has been published 🎉
