### ISSUE TITLE
Possible regression in version parsing

### ISSUE THREAD

**Issue by chrsch-dev** [package-url/packageurl-js#78]
Hi,

since version `2.0.0` the behavior of the parsing of a purl did change:
For version <=1.2.0
```js
PackageURL.fromString('pkg:npm/a@2%2B3').toString() produced `pkg:npm/a@2%2B3`
```

Since version 2.0.0 the output changed
```js
PackageURL.fromString('pkg:npm/a@2%2B3').toString() produced `pkg:npm/a@2+3`
```

Was this change done by intention or is this a regression?

**Comment by chrsch-dev** [comment]
See also #57 for problems with version parsing in the past

**Comment by jdalton** [comment]
@chrsch-dev This is related to #52 and #54 as well. The `+` is allowed in things like query params. The purl spec is about a balance of human readable encoding and percent encoding. Refs:

* https://github.com/package-url/purl-spec/issues/39#issuecomment-479356062
* https://github.com/package-url/purl-spec/issues/39#issuecomment-1720112637
* https://github.com/package-url/purl-spec/pull/261
