### ISSUE TITLE
Correct or incorrect handling of NPM capitalization

### ISSUE THREAD

**Issue by matt-phylum** [package-url/packageurl-js#79]
NPM package names are case sensitive, but the PURL spec says they must be lowercased (https://github.com/package-url/purl-spec/issues/136). This library is adhering to the PURL spec instead of NPM for NPM types, and mangling some rare NPM package names in an unrecoverable way.

Go module paths are case sensitive, but the PURL spec says they must be lowercased, and this library is adhering to the Go rules (mostly) instead of the PURL spec. Should NPM also deviate from the PURL spec?

**Comment by jdalton** [comment]
@matt-phylum 

Thanks for raising this! 
Yep, older names were a bit yolo. 
~~We can leverage npm's [`validate-npm-package-name`](https://www.npmjs.com/package/validate-npm-package-name) package to validate this.~~

**Comment by jdalton** [comment]
@matt-phylum PR up for feedback at #80.

**Comment by jdalton** [comment]
Closed by #80.
